# Generated by Django 3.0.8 on 2020-09-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='title',
        ),
        migrations.AddField(
            model_name='booklist',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='price',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
